export const Error = "\x1b[31m%s\x1b[0m"; // ANSI escape code for red text
export const Green = "\x1b[32m%s\x1b[0m"; // ANSI escape code for green text
export const Blue = "\x1b[34m%s\x1b[0m"; // ANSI escape code for blue text
export const Reset = "\x1b[0m"; // ANSI escape code to reset color
// export const Warning = "\x1b[33m%s\x1b[0m"; // ANSI escape code for yellow text
// export const Success = "\x1b[32m%s\x1b[0m"; // ANSI escape code for green text
// export const Info = "\x1b[34m%s\x1b[0m"; // ANSI escape code for blue text
// export const Underline = "\x1b[4m%s\x1b[0m"; // ANSI escape code for underlined text
// export const Bold = "\x1b[1m%s\x1b[0m"; // ANSI escape code for bold text
// export const Dim = "\x1b[2m%s\x1b[0m"; // ANSI escape code for dim text
// export const Italic = "\x1b[3m%s\x1b[0m"; // ANSI escape code for italic text
// export const Blink = "\x1b[5m%s\x1b[0m"; // ANSI escape code for blinking text
// export const Inverse = "\x1b[7m%s\x1b[0m"; // ANSI escape code for inverse text
// export const Hidden = "\x1b[8m%s\x1b[0m"; // ANSI escape code for hidden text
// export const Strikethrough = "\x1b[9m%s\x1b[0m"; // ANSI escape code for strikethrough text
// export const Black = "\x1b[30m%s\x1b[0m"; // ANSI escape code for black text
// export const Red = "\x1b[31m%s\x1b[0m"; // ANSI escape code for red text
// export const Yellow = "\x1b[33m%s\x1b[0m"; // ANSI escape code for yellow text
// export const Magenta = "\x1b[35m%s\x1b[0m"; // ANSI escape code for magenta text
// export const Cyan = "\x1b[36m%s\x1b[0m"; // ANSI escape code for cyan text
